"""
Append newly discovered (previously unmapped) script entries to
translation_data/script_map.tsv, so they flow through the normal
populate -> translate -> wrap -> relocate -> build pipeline.

Determines n_bytes for each address by scanning forward to the first
single 0x00 byte (the real message terminator per script_decoder.py's
decode_bytes: "if b == 0x00: break").
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from script_decoder import load_encoding, decode_bytes

ROM_PATH = Path("roms/YNAJA4_00.nds")
SCRIPT_MAP_PATH = Path("translation_data/script_map.tsv")
ENCODING_PATH = Path("docs/user_encoding.tsv")
ARM9_RAM_BASE = 0x02000000

# Addresses discovered via find_missing_line.py's brute-force scan.
NEW_VAS = [
    0x020784d4, 0x020784f4, 0x0207861f, 0x0207863c, 0x020786c6,
    0x020786ea, 0x02078744, 0x02078833, 0x02078855, 0x0207895d,
    0x0207897a, 0x0209b9ea, 0x0209d1d3, 0x0209d1f7, 0x0209f916,
    0x0209fd82, 0x020a0109, 0x020a0120, 0x020a09d1, 0x020a1ff5,
    0x020a2005, 0x020a2910, 0x020a3bb0, 0x020a5e5b, 0x020a77d6,
    0x020a77e1, 0x020a97d6, 0x020aa2cd, 0x020abb59, 0x020abb78,
    0x020abe9f, 0x020abebe, 0x020adccd, 0x020b0314, 0x020b102f,
    0x020b103a, 0x020b1dc0, 0x020b248b, 0x020b2b2b, 0x020b2b46,
    0x020b322a, 0x020b659e, 0x020b93d9, 0x020bca82, 0x020bcac1,
    0x020bcae0, 0x020bcb38, 0x020bcb57, 0x020bcb95, 0x020bcc62,
    0x020c7478, 0x020c7866, 0x020c7abb, 0x020c801e, 0x020c80df,
    0x020c840b, 0x020ca4fd, 0x020ca681, 0x020caff8, 0x020cb057,
    0x020cb18f, 0x020cb288, 0x020cb424, 0x020cb4d5,
]


def load_arm9_from_nds(nds_path: Path):
    data = nds_path.read_bytes()
    arm9_rom_offset = int.from_bytes(data[0x20:0x24], "little")
    arm9_load = int.from_bytes(data[0x28:0x2C], "little")
    arm9_size = int.from_bytes(data[0x2C:0x30], "little")
    arm9 = data[arm9_rom_offset:arm9_rom_offset + arm9_size]
    return arm9, arm9_load, arm9_size, arm9_rom_offset


def main():
    print(f"Loading {ROM_PATH} ...")
    arm9, arm9_load, arm9_size, arm9_rom_offset = load_arm9_from_nds(ROM_PATH)
    primary, alternates, states = load_encoding(ENCODING_PATH)

    with open(SCRIPT_MAP_PATH, encoding="utf-8") as f:
        lines = f.readlines()
    hdr = lines[0].rstrip("\n").split("\t")
    i_va = hdr.index("ram_va")

    existing_vas = set()
    for line in lines[1:]:
        if not line.strip():
            continue
        parts = line.rstrip("\n").split("\t")
        if len(parts) > i_va:
            try:
                existing_vas.add(int(parts[i_va], 16))
            except ValueError:
                pass

    new_rows = []
    skipped_existing = 0
    skipped_no_term = 0
    for va in NEW_VAS:
        if va in existing_vas:
            skipped_existing += 1
            continue
        off = va - arm9_load
        # Find the real terminator: first single 0x00 byte, capped search window
        term_off = None
        for p in range(off, min(off + 400, len(arm9))):
            if arm9[p] == 0x00:
                term_off = p
                break
        if term_off is None:
            print(f"  [WARN] no terminator found within 400 bytes for va=0x{va:08x}, skipping")
            skipped_no_term += 1
            continue
        n_bytes = term_off - off + 1

        raw = bytes(arm9[off:off + n_bytes])
        result = decode_bytes(raw, 0, len(raw), primary, alternates, states)

        rom_off = arm9_rom_offset + off
        row = [
            f"0x{va:08x}",
            f"0x{rom_off:08x}",
            str(n_bytes),
            "",  # speaker_id (unknown for these)
            "",  # dup_of_va
            str(result.n_resolved),
            str(result.n_missing),
            str(result.n_out_of_range),
            "",  # decoded (regenerated by populate_script_text.py)
            "",  # english
        ]
        new_rows.append(row)
        print(f"  [ADD] va=0x{va:08x}  n_bytes={n_bytes}  preview={result.text[:50]!r}")

    if new_rows:
        with open(SCRIPT_MAP_PATH, "a", encoding="utf-8") as f:
            for row in new_rows:
                f.write("\t".join(row) + "\n")

    print(f"\nAdded {len(new_rows)} new rows.")
    print(f"Skipped (already present): {skipped_existing}")
    print(f"Skipped (no terminator found): {skipped_no_term}")


if __name__ == "__main__":
    main()
